version: '3'
services:
  c-based:
    image: brauliobalanza/devcontainer:emscripten
    volumes:
      - .:/workspace:cached
    command: /bin/zsh -c "while sleep 1000; do :; done"
  android-runner:
    image: brauliobalanza/devcontainer:android.runner
    volumes:
      - .:/workspace:cached
    ports:
      - "8000"
      - "2019"
      - "2028"
      - "80"
    command: /bin/zsh -c "while sleep 1000; do :; done"
  rust:
    image: brauliobalanza/devcontainer:base
    volumes:
      - .:/workspace:cached
    command: /bin/zsh -c "while sleep 1000; do :; done"