[package]
name = "fannkuchredux"
version = "0.1.0"
authors = ["Jose Balanza"]
description = "A sample project with wasm-pack"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
rayon = "1.5.3"